### ISSUE TITLE
Training permission error

### ISSUE THREAD

**Issue by oliver10345** [wpilibsuite/DetectCoral#20]
Following the training instructions and trying step 6, run the code block.
https://docs.wpilib.org/en/latest/docs/software/examples-tutorials/machine-learning/training.html

We're getting this permission error:
ClientError: An error occurred (AccessDeniedException) when calling the CreateTrainingJob operation: User: arn:aws:sts::308085923257:assumed-role/AmazonSageMaker-ExecutionRole-20200202T132997/SageMaker is not authorized to perform: sagemaker:CreateTrainingJob on resource: arn:aws:sagemaker:us-east-1:308085923257:training-job/wpi-cpu-2020-02-02-21-52-50-104 with an explicit deny

---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-2-ce1d2838730c> in <module>()
     27 # Change this bucket if you want to train with your own data. The WPILib bucket contains thousands of high quality labeled images.
     28 # s3://wpilib
---> 29 estimator.fit("s3://codepurple5827")

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    459         self._prepare_for_training(job_name=job_name)
    460 
--> 461         self.latest_training_job = _TrainingJob.start_new(self, inputs, experiment_config)
    462         self.jobs.append(self.latest_training_job)
    463         if wait:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in start_new(cls, estimator, inputs, experiment_config)
   1012             train_args["enable_sagemaker_metrics"] = estimator.enable_sagemaker_metrics
   1013 
-> 1014         estimator.sagemaker_session.train(**train_args)
   1015 
   1016         return cls(estimator.sagemaker_session, estimator._current_job_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in train(self, input_mode, input_config, role, job_name, output_config, resource_config, vpc_config, hyperparameters, stop_condition, tags, metric_definitions, enable_network_isolation, image, algorithm_arn, encrypt_inter_container_traffic, train_use_spot_instances, checkpoint_s3_uri, checkpoint_local_path, experiment_config, debugger_rule_configs, debugger_hook_config, tensorboard_output_config, enable_sagemaker_metrics)
    549         LOGGER.info("Creating training-job with name: %s", job_name)
    550         LOGGER.debug("train request: %s", json.dumps(train_request, indent=4))
--> 551         self.sagemaker_client.create_training_job(**train_request)
    552 
    553     def process(

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    274                     "%s() only accepts keyword arguments." % py_operation_name)
    275             # The "self" in this scope is referring to the BaseClient.
--> 276             return self._make_api_call(operation_name, kwargs)
    277 
    278         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    584             error_code = parsed_response.get("Error", {}).get("Code")
    585             error_class = self.exceptions.from_code(error_code)
--> 586             raise error_class(parsed_response, operation_name)
    587         else:
    588             return parsed_response

ClientError: An error occurred (AccessDeniedException) when calling the CreateTrainingJob operation: User: arn:aws:sts::308085923257:assumed-role/AmazonSageMaker-ExecutionRole-20200202T132997/SageMaker is not authorized to perform: sagemaker:CreateTrainingJob on resource: arn:aws:sagemaker:us-east-1:308085923257:training-job/wpi-cpu-2020-02-02-21-52-50-104 with an explicit deny

**Comment by oliver10345** [comment]
Tried with the default bucket and got the same error:
estimator.fit("s3://wpilib")

**Comment by GrantPerkins** [comment]
[https://docs.wpilib.org/en/latest/docs/software/examples-tutorials/machine-learning/index.html](https://docs.wpilib.org/en/latest/docs/software/examples-tutorials/machine-learning/index.html)

> We are aware that you will get an exception while trying to train your model with the Jupyter notebook. The WPILib team and Amazon are working hard on a solution and hope to have something in the next few days. Until we do, you will not be able to train your models. We will post the status here as it changes, so please check back often. We are very sorry that this issue occurred and hope to get it resolved as quickly as possible.

**Comment by GrantPerkins** [comment]
If you check #19, there is an effort being made by non-wpilib developers to make the notebook run locally. This could be a short-term solution.
