### ISSUE TITLE
The training.ipynb has disappeared from the root directory.

### ISSUE THREAD

**Issue by JimWright4089** [wpilibsuite/DetectCoral#37]
Hello all,

Say, I was following the instructions:
[https://docs.wpilib.org/en/latest/docs/software/examples-tutorials/machine-learning/training.html](https://docs.wpilib.org/en/latest/docs/software/examples-tutorials/machine-learning/training.html)

I got my Notebook created, and I clicked on the left hand side to find the training.ipynb, and it was not there.

I then rumaged around and found an older version of the file and uploaded it to my AWS Notebook, then changed the S3 name.

It gave me an error:
ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: Access denied for repository: wpi-cpu in registry ID: 118451457254. Please check if your ECR repository and image exist and role arn:aws:iam::422269586304:role/service-role/AmazonSageMaker-ExecutionRole-20200802T022815 has proper pull permissions for SageMaker: ecr:BatchCheckLayerAvailability, ecr:BatchGetImage, ecr:GetDownloadUrlForLayer

I think it was complaining about this line:
ecr_image = "118451457254.dkr.ecr.us-west-2.amazonaws.com/{}:latest".format(algorithm_name)

What should the line be and more importantly, where can I find this in the AWS tools?

-Jim

**Comment by JimWright4089** [comment]
I have found my ecr_image, now however, algorithm_name = 'wpi-cpu'. The WPI-CPU algorithm_name is not correct.

**Comment by GrantPerkins** [comment]
Hi @JimWright4089 ,

Please switch your region to US-East-2 in AWS. 
![image](https://user-images.githubusercontent.com/24625614/89212884-47840f80-d592-11ea-838b-06cde0829539.png)

The ECR containers are hosted in that region. Let me know if that solves it.

**Comment by JimWright4089** [comment]
So I moved everything to Ohio, when I created the notebook, the training and testing notebooks are not on the main branch, so I don't see them in AWS.  I do see them on the aws branch, so I download them off of there and upload it to the aws notebook,  (is the AWS going to be merged back into the main branch?)

After pointing the code to my S3, I got the 'You can download your trained model after the above step tells you "Training job completed".'  Which is cool.

However, is there some other AWS panel that tells me the status of this new job?  I could not find one. 

Forgive me for being verbose on this one issue.  Could you add the output of the AWS step to the Release, even if it's form 2019?  This would have helped me to see what the output should be, also while the notebook is running, I would like to test my Raspberry PI/Coral setup to see if I've got it all setup correctly.

**Comment by GrantPerkins** [comment]
Hi Jim,

We currently do not intend to merge the AWS branch back into master. There is some new stuff in the works that should make this process a lot easier.

As for viewing metrics/status of a training job, the SageMaker page on AWS has a "Training Job" option on the left menu. Choosing the corresponding training job will allow you to view status and some very basic metrics.

For testing your Pi setup, I'd recommend training a model for like ~100 epochs, and then running it, just to see if it all works. It should be fairly plug-and-play, however.

I'm on my phone as it's 2am, so I hope I answered all your questions. Feel free to continuing to use this issue, but I will now mark it as closed.

**Comment by GrantPerkins** [comment]
The output should be a .tar file, which has 2 .tflite files, a .pbtxt, and possibly an accuracy.txt if my memory serves me right.

**Comment by JimWright4089** [comment]
Grant,

Thank you for helping my out with this.  I was mistaken,  my body woke me up, and then my mind took over and wanted to see the output, so I wandered over to my office and found nothing was there.  I think what happened was when I hit run, it cleaned the notebook up and I mistook the last line at the job started.  

Bottom line is I still have this error: ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: Cannot find repository: wpi-cpu in registry ID: 422269586304 Please check if your ECR repository exists and role arn:aws:iam::422269586304:role/service-role/AmazonSageMaker-ExecutionRole-20200804T045654 has proper pull permissions for SageMaker: ecr:BatchCheckLayerAvailability, ecr:BatchGetImage, ecr:GetDownloadUrlForLayer

Should I wait for the new stuff?   Currently the FIRST Washington Fieldhouse is sitting empty and unused, and I have a set of AndyMark frames that I can test in the Fieldhouse so I want to get my hands on as much technology as possible to create tutorials on it.  I was really hoping to show off the DirectCoral stuff.

**Comment by GrantPerkins** [comment]
Hi Andy.

I will double check it works on my accounts. In the meantime, make sure you're in the Ohio region. I will make sure permissions are set correctly.

**Comment by GrantPerkins** [comment]
@JimWright4089 , can you please try again in the North Virginia region? I found some peculiar issues that should hopefully now be resolved.

Also, you can specify which branch of a repo you want to use when creating a notebook instance. I'd recommend using the `aws` branch.

**Comment by JimWright4089** [comment]
> Also, you can specify which branch of a repo you want to use when creating a notebook instance. I'd recommend using the `aws` branch.

I will try both of these things this evening right before I go to bed.

Thank you very much for helping me through this.

**Comment by JimWright4089** [comment]
North Virginia worked.  My job is running.  However, don't count Ohio out yet, there was a step I may not have done when setting up the S3 data source.  Tomorrow I will retry Ohio.  (I can spare the $1 cost in the name of science).

> Also, you can specify which branch of a repo you want to use when creating a notebook instance. I'd recommend using the `aws` branch.

When creating the notebook the git url can't (or at least I could not find a way) specify a branch.  However, hitting the GIT icon when in the actual notebook allowed me to change it.

**Comment by GrantPerkins** [comment]
Ohio will not work. The ECR iamge is hosted is North Virginia, and is not visible in other regions.

In the create new notebook instance page of SageMaker, you select a repository to use.
![image](https://user-images.githubusercontent.com/24625614/89439781-ad020880-d718-11ea-86c3-335f1d0b3f46.png)
Choose add new repository -> GitHub repository, then you can choose the branch in the circle area in the picture below.
![image](https://user-images.githubusercontent.com/24625614/89439887-d7ec5c80-d718-11ea-9966-81e3937ef1ca.png)

**Comment by JimWright4089** [comment]
Ahh, ok, I won't try it then.
